### ISSUE TITLE
Error when not specifying DC 

### ISSUE THREAD

**Issue by JRN-BE** [Friends-Security/ShadowHound#2]
When not specifying a domain controller, the script refuses to run in my testing... So the first use case that you specify isn't correct.

**Comment by yudasm** [comment]
Did you run it on a PC that is domain joined? If so, please let me know what the error was
Is the user who was running the script also a domain user or a local user?
Thanks

**Comment by yudasm** [comment]
Thank you very much for the feedback!
I believe I fixed this issue - made a minor adjustment to the -Server variable handling in both the ADM and DS version.
Let me know if it works now so I can close this

**Comment by JRN-BE** [comment]
Nope, doens't change anything for me... Still the same.

**Comment by yudasm** [comment]
Which version are you using? The DS one or the AD Module one?

**Comment by JRN-BE** [comment]
I stand corrected, I ran both scripts again and now they function as expected.
